[build]
  command = "npm run build"
  publish = "dist"

# Optional: Settings for different deploy contexts
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"